/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        ep: {
          accent: '#F5B82D',
          'accent-hover': '#E0A724',
          'accent-soft': 'rgb(var(--ep-accent-soft-rgb) / <alpha-value>)',
          'accent-muted': '#F3D893',
          'accent-foreground': '#1C1A16',
          surface: 'rgb(var(--ep-surface-rgb) / <alpha-value>)',
          'surface-muted': 'rgb(var(--ep-surface-muted-rgb) / <alpha-value>)',
          'surface-panel': 'rgb(var(--ep-surface-panel-rgb) / <alpha-value>)',
          line: 'rgb(var(--ep-line-rgb) / <alpha-value>)',
          muted: 'rgb(var(--ep-muted-rgb) / <alpha-value>)',
          ink: 'rgb(var(--ep-ink-rgb) / <alpha-value>)',
          subtle: 'rgb(var(--ep-subtle-rgb) / <alpha-value>)',
          faint: 'rgb(var(--ep-faint-rgb) / <alpha-value>)',
          glow: 'rgb(var(--ep-glow-rgb) / <alpha-value>)',
          success: '#4CA86D',
          'success-soft': 'rgb(var(--ep-success-soft-rgb) / <alpha-value>)',
          'success-border': 'rgb(var(--ep-success-border-rgb) / <alpha-value>)',
          'success-text': 'rgb(var(--ep-success-text-rgb) / <alpha-value>)',
          'danger-soft': 'rgb(var(--ep-danger-soft-rgb) / <alpha-value>)',
          'danger-border': 'rgb(var(--ep-danger-border-rgb) / <alpha-value>)',
          'danger-text': 'rgb(var(--ep-danger-text-rgb) / <alpha-value>)',
          overlay: 'rgb(var(--ep-overlay-rgb) / <alpha-value>)',
          skeleton: 'rgb(var(--ep-skeleton-rgb) / <alpha-value>)',
          saved: 'rgb(var(--ep-saved-rgb) / <alpha-value>)',
          'saved-hover': 'rgb(var(--ep-saved-hover-rgb) / <alpha-value>)',
          'case-story-text': 'rgb(var(--ep-case-story-text-rgb) / <alpha-value>)',
          'case-violet-soft': 'rgb(var(--ep-case-violet-soft-rgb) / <alpha-value>)',
          'case-violet-text': 'rgb(var(--ep-case-violet-text-rgb) / <alpha-value>)',
          'case-amber-soft': 'rgb(var(--ep-case-amber-soft-rgb) / <alpha-value>)',
          'case-amber-text': 'rgb(var(--ep-case-amber-text-rgb) / <alpha-value>)',
          'case-parable-soft': 'rgb(var(--ep-case-parable-soft-rgb) / <alpha-value>)',
          'case-parable-text': 'rgb(var(--ep-case-parable-text-rgb) / <alpha-value>)',
          blue: '#F5B82D',
          'blue-hover': '#E0A724',
        },
        logos: {
          accent: '#F5B82D',
          'accent-soft': 'rgb(var(--ep-accent-soft-rgb) / <alpha-value>)',
          ink: 'rgb(var(--ep-ink-rgb) / <alpha-value>)',
        },
      },
      fontFamily: {
        sans: ['var(--font-study-sans)', 'system-ui', 'sans-serif'],
      },
      borderRadius: {
        card: '28px',
        pill: '9999px',
      },
      boxShadow: {
        card: '0 10px 40px rgb(26 25 23 / 0.06), 0 2px 8px rgb(26 25 23 / 0.03)',
        'card-lg': '0 16px 48px rgb(26 25 23 / 0.08), 0 4px 12px rgb(26 25 23 / 0.04)',
        soft: '0 6px 24px rgb(245 184 45 / 0.12)',
        innerSoft: 'inset 0 1px 1px rgb(26 25 23 / 0.04)',
      },
    },
  },
  plugins: [],
};
